Simon8029.EMPDemo.WebApp/Areas/EmailMarketing/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Simon8029.EMPDemo.Model;
using Simon8029.EMPDemo.Model.ModelsForEasyUI;
using Simon8029.EMPDemo.Repository;
using Simon8029.EMPDemo.WebApp.Areas.EmailMarketing.Models;
using Simon8029.EMPDemo.WebApp.Controllers;

namespace Simon8029.EMPDemo.WebApp.Areas.EmailMarketing.Controllers
{
    public class SummaryController : BaseController
    {
        // GET: EmailMarketing/Summary
        [HttpGet]
        public ActionResult SummaryForSubmit(int id)
        {
            var campaignSummary = OperationContext.ServiceSession.EM_CampaignsService.Get(c => c.CampaignID == id).FirstOrDefault();
            
            return View(campaignSummary);
        }

        [HttpPost]
        public ActionResult SummaryForSubmit(int id, FormCollection form)
        {
            var campaign = OperationContext.ServiceSession.EM_CampaignsService.Get(c => c.CampaignID == id).FirstOrDefault();
            if (campaign != null)
            {
                campaign.Submitted = true;
                OperationContext.ServiceSession.SaveChange();
                return OperationContext.SendAjaxMessage(AjaxMessageStatus.OperationSuccess, "", "", null);
            }
            else
            {
                return OperationContext.SendAjaxMessage(AjaxMessageStatus.OperationFailed, "campaign is not found", "",
                    null);
            }
        }

        [HttpGet]
        public ActionResult SummaryForApprove(int id)
        {
            var campaignSummary = OperationContext.ServiceSession.EM_CampaignsService.Get(c => c.CampaignID == id).FirstOrDefault();
            var hasApproveCampaignPermission =
                OperationContext.CurrentUserPermissions.Where(p => p.permissionActionName == "ApproveCampaign")
                    .FirstOrDefault() != null;
            ViewBag.HasApproveCampaignPermission = hasApproveCampaignPermission;
            return View(campaignSummary);
        }
        [HttpPost]
        public ActionResult SummaryForApprove(int id, FormCollection form)
        {
           

            var campaign = OperationContext.ServiceSession.EM_CampaignsService.Get(c => c.CampaignID == id).FirstOrDefault();
            if (campaign != null)
            {
                campaign.Approved = true;
                campaign.ApprovedBy = OperationContext.CurrentUser.employeeLoginName;
                campaign.ApprovedDate=DateTime.Now;
                OperationContext.ServiceSession.SaveChange();

                //invoke stored procedure, populate data to campaignInstance.
                Entities entity = new Entities();
                var emailInstanceId =
                    OperationContext.ServiceSession.EM_EmailInstancesService.Get(e => e.CampaignID == id)
                        .FirstOrDefault()
                        .EmailInstanceID;
                entity.EM_CampaignInstances_INSERT(emailInstanceId);

                return OperationContext.SendAjaxMessage(AjaxMessageStatus.OperationSuccess, "", "", null);
            }
            else
            {
                return OperationContext.SendAjaxMessage(AjaxMessageStatus.OperationFailed, "campaign is not found", "",
                    null);
            }
        }
    }
}

Simon8029.EMPDemo.WebApp/Areas/EmailMarketing/Views/Summary/SummaryForApprove.cshtml
@model Simon8029.EMPDemo.Model.EM_Campaigns

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    function approveCampaign() {
        $.messager.confirm("Info", "Approve Campaign?", function (r) {
            if (r) {
                var form = $("#campaignForm");
                form.submit();
            }
        });
    };

    function complete(data) {
        $.globalHelper.reloadSeletecTabDataGrid();
        $.globalHelper.closeCommonWindow();
    };

    //$("#buttonId").click(function () {
    //    if (confirm("Are you sure you want to create Id " + $("#CustomerId").val() + " ?")) {
    //        $("#campaignForm").submit(); // Submitting the form if user clicks OK
    //    }
    //});

    //$("#cancel").click(function () {
    //    $.globalHelper.closeCommonWindow();
    //});

    function closeCommonWindow() {
        $.globalHelper.closeCommonWindow();
    }

</script>

<h2>Summary</h2>

@using (Ajax.BeginForm("SummaryForApprove", "Summary", new AjaxOptions() { OnComplete = "complete" }, new { @id = "campaignForm" }))
{
    <table class="tbList">
        <tr>
            <td>@Html.DisplayNameFor(o => o.CampaignID)</td>
            <td>@Html.TextBoxFor(o => o.CampaignID)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.StartDate)</td>
            <td>@Html.TextBoxFor(o => o.StartDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.EndDate)</td>
            <td>@Html.TextBoxFor(o => o.EndDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CampaignName)</td>
            <td>@Html.TextBoxFor(o => o.CampaignName)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CampaignDesc)</td>
            <td>@Html.TextBoxFor(o => o.CampaignDesc)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CreatedBy)</td>
            <td>@Html.TextBoxFor(o => o.CreatedBy)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CreatedDate)</td>
            <td>@Html.TextBoxFor(o => o.CreatedDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.UpdatedBy)</td>
            <td>@Html.TextBoxFor(o => o.UpdatedBy)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.UpdatedDate)</td>
            <td>@Html.TextBoxFor(o => o.UpdatedDate)</td>
        </tr>


        <hr />

        @if (@Model.EM_EmailInstances.Count > 0)
        {
            <tr>
                <td>@Html.DisplayNameFor(o => o.EM_EmailInstances.First().SubjectLine)</td>
                <td>@Html.TextBoxFor(o => o.EM_EmailInstances.First().SubjectLine)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(o => o.EM_EmailInstances.First().EmailBody)</td>
                <td>@Html.TextBoxFor(o => o.EM_EmailInstances.First().EmailBody)</td>
            </tr>
        }

        <tr>
            <td colspan="3">
                @if (ViewBag.HasApproveCampaignPermission)
                {
                    <input type="button" id="approveButton" value="Approve" onclick="approveCampaign()" />
                    <input type="button" id="cancel" value="Cancel" onclick="closeCommonWindow()" />
                }
                else
                {

                    <input type="button" id="Ok" value="Ok" onclick="closeCommonWindow()" />
                }
            </td>
        </tr>
    </table>
}

Simon8029.EMPDemo.WebApp/Areas/EmailMarketing/Views/Summary/SummaryForSubmit.cshtml
@model Simon8029.EMPDemo.Model.EM_Campaigns

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    
    function begin(){}
    function complete() {
        $.messager.alert("Info", "Submit campaign?", "info", function() {
            @*$.ajax({
                type: "POST",
                url: "/EmailMarketing/Summary/SubmitCampaign",
                data: { id: @Model.CampaignID, approvedBy: $.post("/EmailMarketing/Summary/GetCurrentUserName") },
                success: success,
                dataType: dataType
            });*@

            $.post('/EmailMarketing/Summary/SubmitCampaign', { id: @Model.CampaignID});

            $.globalHelper.reloadSeletecTabDataGrid();
            $.globalHelper.closeCommonWindow();
        });
    };

    function goBack() {
        $.messager.alert("Info", "Back to previous page?", "info", function () {
            $.globalHelper.reloadSeletecTabDataGrid();
            $.globalHelper.closeCommonWindow();

            $.globalHelper.showCommonWindow("Modify Email", "/emailmarketing/Campaigns/Modify/@Model.CampaignID", 450, 560);

        });
    }

</script>

<h2>Summary</h2>

@using (Ajax.BeginForm(new AjaxOptions() { OnBegin = "begin", OnComplete = "complete" }))
{
    <table class="tbList">
        <tr>
            <td>@Html.DisplayNameFor(o => o.CampaignID)</td>
            <td>@Html.TextBoxFor(o => o.CampaignID)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.StartDate)</td>
            <td>@Html.TextBoxFor(o => o.StartDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.EndDate)</td>
            <td>@Html.TextBoxFor(o => o.EndDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CampaignName)</td>
            <td>@Html.TextBoxFor(o => o.CampaignName)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CampaignDesc)</td>
            <td>@Html.TextBoxFor(o => o.CampaignDesc)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CreatedBy)</td>
            <td>@Html.TextBoxFor(o => o.CreatedBy)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.CreatedDate)</td>
            <td>@Html.TextBoxFor(o => o.CreatedDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.UpdatedBy)</td>
            <td>@Html.TextBoxFor(o => o.UpdatedBy)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(o => o.UpdatedDate)</td>
            <td>@Html.TextBoxFor(o => o.UpdatedDate)</td>
        </tr>

        @if (@Model.EM_EmailInstances.Count > 0)
        {
            <tr>
                <td>@Html.DisplayNameFor(o => o.EM_EmailInstances.First().SubjectLine)</td>
                <td>@Html.TextBoxFor(o => o.EM_EmailInstances.First().SubjectLine)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(o => o.EM_EmailInstances.First().EmailBody)</td>
                <td>@Html.TextBoxFor(o => o.EM_EmailInstances.First().EmailBody)</td>
            </tr>
        }


        <tr>
            <td colspan="3">
                <input type="button" value="Back" onclick="goBack"/>
                <input type="submit" value="Submit" />
            </td>
        </tr>
    </table>
}

